abbreviation_dict = {
    "abt": "about",
    "afaik": "as far as I know",
    "afk": "away from keyboard",
    "aka": "also known as",
    "ama": "ask me anything",
    "asap": "as soon as possible",
    "atm": "at the moment",
    "b/c": "because",
    "b4": "before",
    "bae": "before anyone else",
    "bc": "be careful",
    "bday": "birthday",
    "bff": "best friends forever",
    "bfn": "bye for now",
    "bk": "back",
    "brb": "be right back",
    "btw": "by the way",
    "c/o": "care of",
    "cya": "see you",
    "dnd": "do not disturb",
    "dm": "direct message",
    "eod": "end of day",
    "eta": "estimated time of arrival",
    "fb": "Facebook",
    "ff": "follow Friday",
    "fomo": "fear of missing out",
    "ftl": "for the loss",
    "ftw": "for the win",
    "fwiw": "for what it's worth",
    "fyi": "for your information",
    "gg": "good game",
    "gl": "good luck",
    "gtg": "got to go",
    "hbd": "happy birthday",
    "hmu": "hit me up",
    "ht": "hat tip",
    "icymi": "in case you missed it",
    "idc": "I don't care",
    "idk": "I don't know",
    "iirc": "if I recall correctly",
    "ikr": "I know, right?",
    "imho": "in my humble opinion",
    "imo": "in my opinion",
    "irl": "in real life",
    "j/k": "just kidding",
    "jfyi": "just for your information",
    "jk": "just kidding",
    "kk": "okay",
    "lmao": "laughing my ass off",
    "lmk": "let me know",
    "lol": "laugh out loud",
    "mfw": "my face when",
    "myob": "mind your own business",
    "nbd": "no big deal",
    "nm": "not much",
    "np": "no problem",
    "nsfw": "not safe for work",
    "nth": "nothing",
    "oic": "oh, I see",
    "omg": "oh my god",
    "omw": "on my way",
    "otp": "one true pairing",
    "pebkac": "problem exists between keyboard and chair",
    "pov": "point of view",
    "qt": "cutie",
    "rofl": "rolling on the floor laughing",
    "rpg": "role-playing game",
    "rt": "retweet",
    "smh": "shaking my head",
    "srsly": "seriously",
    "tbh": "to be honest",
    "tgif": "thank god it's Friday",
    "thx": "thanks",
    "tl;dr": "too long; didn't read",
    "tmi": "too much information",
    "ttyl": "talk to you later",
    "ty": "thank you",
    "w/e": "whatever",
    "w/o": "without",
}
